name: Maya
favicon: null
layout_spectrum: 0.4909
typography_spectrum: 0.89334
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e7e3'
    - '#aaa399'
    - '#5a4d3d'
    - '#8c7f6f'
    - '#211c18'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
