layout_spectrum: 0.6719157716725022
typography_spectrum: 0.63964789127931
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.5382128790952265
  lightness: 0.9184479075483978
  saturation: 0.6532176565378904
  rhythmicContrast: 0.6920978147536516
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-35516913-1
  facebook: null
  twitter: null
name: Maya
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: carpenter of my soul
    id: f8cb6eb1-55d3-4465-8c63-6cdf626b9e72
    type: content
  - name: filters
    id: fd59d44b-4a64-454e-9dfd-7f9edf10102f
    type: content
  - name: abundant greens
    id: da0f312c-37a2-475c-8f6b-de2549833cce
    type: content
  - name: a rainbow  on her head
    id: 008e65af-a5fa-4119-b4e3-c373172da190
    type: content
  - name: anew each day
    id: c607f420-d54d-487f-8d9d-cbccc04b221e
    type: content
  - name: a messy mess
    id: 987c3ac3-22be-454b-b489-d15fd3daaeaa
    type: content
  - name: a greeting machine
    id: 1806a0e0-193d-43cf-b67f-6c4cb592165c
    type: content
  - name: a good poem
    id: 35b5cf26-42c0-4a16-8ccd-1790bfdff197
    type: content
  - name: ' Good news '
    id: 101f8049-738d-4433-9921-4585060f13bf
    type: content
  - name: Maya Running
    id: 2fc9f40d-5184-459b-8542-b39c0ddf7c0d
    type: content
  - name: Abundant Greens 2
    id: 2fab286a-fab0-48ad-9b83-f611f735af54
    type: content
  - name: Stay in that place
    id: 33736867-3511-4009-811f-477e112b9e1c
    type: content
  - name: What are dreams
    id: 4afea7a6-a8c8-4acd-990a-033f24b799c4
    type: content
favicon: null
purpose: []
