name: Maya
favicon: null
layout_spectrum: 0.90635
typography_spectrum: 0.86146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040402'
    - '#4e391a'
    - '#834e1c'
    - '#b59241'
    - '#ded2b8'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
