name: Maya
favicon: null
layout_spectrum: 0.1243
typography_spectrum: 0.70777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7d3d2'
    - '#fcfcfc'
    - '#7a7a84'
    - '#040406'
    - '#47464c'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
